spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/weather?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
#    url: jdbc:mysql://database-1.c1lr5qm36wbs.ap-northeast-2.rds.amazonaws.com:3306/weatherdb?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
#    username: weathermaster
#    password: weather2022
    username: root
    password: 20172025
  session:
    store-type: jdbc
  jpa:
    properties:
      hibernate.format_sql: true
    hibernate:
      ddl-auto: update
    generate-ddl-auto: create
    show_sql: true
